import type { User, Post, Notification } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1", name: "Kartik", email: "kartik@locult.in", password: "demo123",
    community: "Bhayandar West", organization: "DBIT",
    address: "203, Sai Residency, Station Road", city: "Bhayandar", district: "Thane", pincode: "401101",
    trustScore: 85, postsShared: 12, verified: 28, helpfulContributions: 45,
    badges: ["Verified Contributor", "Community Helper"], following: ["u2", "u3"], saved: ["p2", "p4"],
  },
  {
    id: "u2", name: "Priya", email: "priya@locult.in", password: "demo123",
    community: "Mira Road", organization: "DBIT",
    address: "501, Harmony Heights", city: "Mira Road", district: "Thane", pincode: "401107",
    trustScore: 72, postsShared: 8, verified: 15, helpfulContributions: 22,
    badges: ["Helpful Reporter"], following: ["u1"], saved: ["p1"],
  },
  {
    id: "u3", name: "Rajesh", email: "rajesh@locult.in", password: "demo123",
    community: "Bhayandar West",
    address: "12, Market Lane", city: "Bhayandar", district: "Thane", pincode: "401101",
    trustScore: 65, postsShared: 5, verified: 10, helpfulContributions: 18,
    badges: ["Local Guide"], following: ["u1"], saved: [],
  },
  {
    id: "u4", name: "Vikram", email: "vikram@locult.in", password: "demo123",
    community: "DBIT Campus", organization: "DBIT",
    address: "DBIT, Kurla-Funda Road", city: "Mumbai", district: "Mumbai Suburban", pincode: "400070",
    trustScore: 92, postsShared: 25, verified: 60, helpfulContributions: 88,
    badges: ["Verified Contributor", "Community Helper", "Opportunity Scout"],
    following: ["u1", "u2", "u3"], saved: ["p3"],
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1", authorId: "u3", category: "Local Issue", urgency: "Important",
    title: "Road Blockage Near Station Road",
    description: "A large tree has fallen near the station road entrance. Traffic is heavily congested. Please avoid this route if possible. Municipal teams have been informed.",
    location: { name: "Station Road, Bhayandar West", lat: 19.2965, lng: 72.8482, pincode: "401101", district: "Thane" },
    status: "Under Review", validUntil: "2026-10-03T23:59:00", createdAt: "2026-10-02T08:30:00", updatedAt: "2026-10-02T08:30:00",
    tags: ["road", "traffic", "bhayandar"],
    upvotes: 24, downvotes: 1, upvotedBy: ["u1", "u4"], downvotedBy: [], views: 128,
    comments: [
      { id: "c1", authorId: "u1", authorName: "Kartik", content: "Can confirm, saw it while commuting. Very large tree blocking the entire left lane.", timestamp: "2026-10-02T09:00:00", upvotes: 8, downvotes: 0, isPinned: false, isOfficialReply: false,
        replies: [{ id: "c1r1", authorId: "u3", authorName: "Rajesh", content: "Thanks for confirming. Municipal crew arrived about 20 minutes ago.", timestamp: "2026-10-02T09:15:00", upvotes: 3, downvotes: 0, isPinned: false, isOfficialReply: true, replies: [] }],
      },
    ],
    repostCount: 7, shareCount: 15, verifyScore: 45, verifiedBy: ["u1", "u4"], reportCount: 0, reportedBy: [],
  },
  {
    id: "p2", authorId: "u2", category: "Emergency", urgency: "Emergency",
    title: "Severe Waterlogging on Highway",
    description: "Water level rising rapidly on the main highway intersection. Multiple cars stalled. Take alternate routes immediately! Rescue teams have been notified.",
    location: { name: "Highway Intersection, Mira Road", lat: 19.2815, lng: 72.866, pincode: "401107", district: "Thane" },
    status: "Active", validUntil: "2026-10-02T23:59:00", createdAt: "2026-10-02T10:30:00", updatedAt: "2026-10-02T10:45:00",
    tags: ["waterlogging", "highway", "emergency"],
    upvotes: 112, downvotes: 2, upvotedBy: ["u1", "u3", "u4"], downvotedBy: [], views: 540,
    comments: [
      { id: "c2", authorId: "u4", authorName: "Vikram", content: "NDRF team spotted near the junction. Stay safe everyone.", timestamp: "2026-10-02T10:50:00", upvotes: 25, downvotes: 0, isPinned: true, isOfficialReply: false, replies: [] },
    ],
    repostCount: 34, shareCount: 89, verifyScore: 92, verifiedBy: ["u1", "u3", "u4"], reportCount: 0, reportedBy: [],
  },
  {
    id: "p3", authorId: "u4", category: "Internship", urgency: "Normal",
    title: "Frontend Developer Internship — ABC Technologies",
    description: "ABC Technologies is looking for 3 frontend interns for a 6-month paid program. React/Next.js skills required. Stipend: Rs.15,000/month. Apply before Oct 15.",
    location: { name: "Mira Road", lat: 19.281, lng: 72.8645, pincode: "401107", district: "Thane" },
    status: "Verified", validUntil: "2026-10-15T23:59:00", createdAt: "2026-10-01T14:00:00", updatedAt: "2026-10-01T14:00:00",
    tags: ["internship", "frontend", "react", "nextjs"],
    upvotes: 89, downvotes: 0, upvotedBy: ["u1", "u2"], downvotedBy: [], views: 320,
    comments: [
      { id: "c3", authorId: "u2", authorName: "Priya", content: "Is remote work available for this internship?", timestamp: "2026-10-01T15:00:00", upvotes: 5, downvotes: 0, isPinned: false, isOfficialReply: false,
        replies: [{ id: "c3r1", authorId: "u4", authorName: "Vikram", content: "Yes, hybrid model — 2 days on-campus, 3 days remote.", timestamp: "2026-10-01T15:30:00", upvotes: 12, downvotes: 0, isPinned: false, isOfficialReply: true, replies: [] }],
      },
    ],
    repostCount: 12, shareCount: 45, verifyScore: 100, verifiedBy: ["u1", "u2", "u3"], reportCount: 0, reportedBy: [],
  },
  {
    id: "p4", authorId: "u1", category: "Lost & Found", urgency: "Important",
    title: "Black Wallet Found Near College Gate",
    description: "Found a black leather wallet on the 2nd floor near the library entrance. It contains some ID cards. If this is yours, please submit a claim with a description of the wallet contents.",
    location: { name: "Approx. 250m radius (Privacy Fuzzed)", lat: 19.2462, lng: 72.857, pincode: "400070", district: "Mumbai Suburban", fuzzed: true },
    status: "Active", validUntil: "2026-10-05T23:59:00", createdAt: "2026-10-01T09:00:00", updatedAt: "2026-10-01T09:00:00",
    tags: ["wallet", "lost", "found", "college"],
    upvotes: 12, downvotes: 0, upvotedBy: ["u4"], downvotedBy: [], views: 85,
    comments: [], repostCount: 3, shareCount: 8, verifyScore: 75, verifiedBy: ["u4"], reportCount: 0, reportedBy: [],
    claimChallenge: "Describe the color of the card holder and the number of cards inside.", claimStatus: "unclaimed",
  },
  {
    id: "p5", authorId: "u4", category: "Event", urgency: "Normal",
    title: "Community Blood Donation Camp",
    description: "Annual blood donation camp organized by Red Cross in collaboration with the local community center. Walk-ins welcome. Please bring a valid ID.",
    location: { name: "Community Hall, Bhayandar", lat: 19.297, lng: 72.849, pincode: "401101", district: "Thane" },
    status: "Verified", validUntil: "2026-10-05T18:00:00", createdAt: "2026-09-30T10:00:00", updatedAt: "2026-09-30T10:00:00",
    tags: ["blood", "donation", "health", "event"],
    upvotes: 56, downvotes: 0, upvotedBy: ["u1", "u2", "u3"], downvotedBy: [], views: 210,
    comments: [], repostCount: 18, shareCount: 32, verifyScore: 100, verifiedBy: ["u1", "u2", "u3"], reportCount: 0, reportedBy: [],
  },
  {
    id: "p6", authorId: "u2", category: "Scholarship", urgency: "Normal",
    title: "State Merit Scholarship — Last Date Oct 20",
    description: "Maharashtra State Merit Scholarship applications are open. Students with 75%+ in HSC are eligible. Financial aid up to Rs.50,000 per year.",
    location: { name: "Maharashtra", lat: 19.25, lng: 72.858, pincode: "400070", district: "Mumbai Suburban" },
    status: "Active", validUntil: "2026-10-20T23:59:00", createdAt: "2026-09-28T12:00:00", updatedAt: "2026-09-28T12:00:00",
    tags: ["scholarship", "merit", "maharashtra"],
    upvotes: 45, downvotes: 0, upvotedBy: [], downvotedBy: [], views: 180,
    comments: [], repostCount: 8, shareCount: 22, verifyScore: 88, verifiedBy: ["u4"], reportCount: 0, reportedBy: [],
  },
  {
    id: "p7", authorId: "u3", category: "Announcement", urgency: "Important",
    title: "Water Supply Disruption — Oct 3-4",
    description: "Scheduled maintenance by MWSC will cause water supply disruption in Bhayandar West on October 3rd and 4th from 8 AM to 6 PM. Please store water in advance.",
    location: { name: "Bhayandar West", lat: 19.2955, lng: 72.8475, pincode: "401101", district: "Thane" },
    status: "Verified", validUntil: "2026-10-04T18:00:00", createdAt: "2026-10-01T16:00:00", updatedAt: "2026-10-01T16:00:00",
    tags: ["water", "maintenance", "advisory"],
    upvotes: 67, downvotes: 3, upvotedBy: ["u1", "u2", "u4"], downvotedBy: [], views: 300,
    comments: [], repostCount: 22, shareCount: 55, verifyScore: 95, verifiedBy: ["u1", "u2", "u4"], reportCount: 0, reportedBy: [],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "emergency", title: "Emergency Alert Nearby", message: "Severe Waterlogging on Highway — 1.2km from you", timestamp: "2026-10-02T10:35:00", read: false, postId: "p2" },
  { id: "n2", type: "verified", title: "Post Verified", message: "Your post 'Black Wallet Found' was verified by 1 community member", timestamp: "2026-10-02T09:00:00", read: false, postId: "p4" },
  { id: "n3", type: "update_suggested", title: "Update Suggested", message: "Someone suggested an update to 'Road Blockage Near Station Road'", timestamp: "2026-10-02T08:45:00", read: true, postId: "p1" },
  { id: "n4", type: "expiring", title: "Post Approaching Expiry", message: "Your post 'Black Wallet Found' expires in 3 days", timestamp: "2026-10-02T07:00:00", read: true, postId: "p4" },
  { id: "n5", type: "update_accepted", title: "Update Accepted", message: "Your update to 'Water Supply Disruption' was accepted", timestamp: "2026-10-01T17:00:00", read: true, postId: "p7" },
  { id: "n6", type: "claim_request", title: "Claim Request Received", message: "Someone wants to claim 'Black Wallet Found Near College Gate'", timestamp: "2026-10-02T10:00:00", read: false, postId: "p4" },
];
